version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080

  nginx:
    image: dides_helpdesk_nginx_image
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media  # Serve media files
